gui:
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 2
  language: en
  # use the mocha catppuccin theme
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    selectedRangeBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
  showNumstatInFilesView: true

git:
  paging:
    colorArg: always
    pager: delta -s --dark --paging=never --24-bit-color=never
  parseEmoji: true
